project:
  type: website
  output-dir: "."

website:
  title: "Sophia Rodger"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
      - text: Homework
        href: hw.qmd
           
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© Sophia Rodger, 2023"

format:
  html:
    theme: 
      lightgi: quartz
      dark: darkly
    mainfont: system-ui; 
    highlight-style: espresso # atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
